
name: Deploy dist folder
"on": [push, workflow_dispatch]
jobs:
  run_tests:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v5
        # run: |
        #   echo "Getting code"
        #   git clone "${{toJson(github)}}"
        #   git clone https://github.com/sujal12344/AI-Companion-Builder.git